 git add Figs/CloudAnom/Desc/*.fig
 git add Figs/CloudAnom/Desc/*.png
 git add Figs/CloudAnom/Desc_ocean/*.png
 git add Figs/CloudAnom/Desc_ocean/*.fig
 git add Figs/ClearAnom/*.fig
 git add Figs/ClearAnom/*.png
 git add Figs/CloudAnom/Desc_ocean/*.mat
 git add Figs/CloudAnom/Desc/*.mat
 git add Figs/CloudAnom/Desc_ocean_orig/*.mat
 git add Figs/CloudAnom/Desc_ocean_orig/*.png
 git add Figs/CloudAnom/Desc_ocean_orig/*.fig
